# CI workflow for validating action
name: analysis
on: [push]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run PSRule
      uses: BernieWhite/PSRule-actions@master
      with:
        source: '.rule/'
