# CI workflow for validating action
name: Build
on: [push]
jobs:
  run:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run PSRule
      uses: ./
      with:
        inputType: repository
        modules: PSRule.Rules.Azure, PSRule.Rules.Kubernetes
