# CI workflow for validating action
name: Build
on: [push]
jobs:
  run:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      env:
        advice.detachedHead: false
    - name: Run PSRule
      uses: ./
      with:
        source: '.ps-rule/'
